/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.views;

import bkap.dao.impl.CategoryServiceDAO;
import bkap.dao.impl.ProductDAO;
import bkap.dao.impl.ServiceDAO;
import bkap.model.CategoryService;
import bkap.model.Service;
import java.awt.CardLayout;
import java.awt.Checkbox;
import java.awt.CheckboxGroup;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Label;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import javax.swing.border.Border;

/**
 *
 * @author hongb
 */
public class ListServiceJDialog extends javax.swing.JDialog {

    private ProductDAO proDao = new ProductDAO();
    private ServiceDAO serDao = new ServiceDAO();
    private CategoryServiceDAO catSerDao = new CategoryServiceDAO();
    private List<Service> listSer;
    private List<CategoryService> listCatSer;
    private List<Integer> listRoomSelected;
    private DefaultComboBoxModel modelListRoom;
    private List<List> listServiceSelected;
    private List<Integer> listServiceitem;
    private JPanel pnl;
    private int indexSelected;
    private Border blackline;
    private JCheckBox[] checkbox;
    private JList l;

    /**
     * Creates new form ListServiceJDialog
     */
    public ListServiceJDialog(java.awt.Frame parent, boolean modal, List<Integer> listRoom) {
        super(parent, modal);
        initComponents();

        this.listRoomSelected = listRoom;
        listSer = serDao.findAll();
        listCatSer = catSerDao.findAll();

        modelListRoom = (DefaultComboBoxModel) cbRoom.getModel();
        setComboxModel();
        pnlContainer.setLayout(new CardLayout());
        indexSelected = cbRoom.getSelectedIndex();
        createNewPanel(indexSelected);
    }

    private void setComboxModel() {
        modelListRoom.addElement("Tất cả");
        for (Integer listR : listRoomSelected) {
            modelListRoom.addElement("Phòng " + listR);
        }
    }

    private void createNewPanel(int index) {
        pnlContainer.removeAll();
        if(pnl != null){
            pnl.removeAll();
        }else{
            pnl = new JPanel();
        }
        for (CategoryService listC : listCatSer) {
            getItemService(listC.getId());
        }
        pnlContainer.add(pnl);
        pnl.setLayout(new GridLayout(listCatSer.size(), 1));
        pnl.setVisible(true);
        pnl.validate();
    }

    private void getItemService(int id) {
        JPanel pnlItem = new JPanel();
        for (CategoryService listC : listCatSer) {
            if (id == listC.getId()) {
                blackline = BorderFactory.createTitledBorder(listC.getName());
            }
        }

        checkbox = new JCheckBox[listSer.size()];
        pnlItem.setBorder(blackline);
        pnlItem.setLayout(new FlowLayout(5));
        int index = 0;
        for (Service list : listSer) {
            if (id == list.getCatService()) {
                checkbox[index] = new JCheckBox(list.getName(), false);
                pnlItem.add(checkbox[index]);
                index++;
            }
        }
        pnl.add(pnlItem);
        pnlItem.setVisible(true);
        pnlItem.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbRoom = new javax.swing.JComboBox();
        pnlContainer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbRoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRoomItemStateChanged(evt);
            }
        });

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainer.setAutoscrolls(true);
        pnlContainer.setLayout(new java.awt.CardLayout());

        jButton1.setText("Thêm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbRoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 455, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRoomItemStateChanged
        // TODO add your handling code here:
        
        createNewPanel(indexSelected);
        if (checkbox != null) {
            printSelectedNames(checkbox);
        } else {
//            createNewPanel(indexSelected);
            System.out.println("aaaaaaa");
        }
    }//GEN-LAST:event_cbRoomItemStateChanged
    public void printSelectedNames(JCheckBox[] boxes) {
        if (boxes == null) {
            System.out.println("false");
        } else {
            System.out.println("true");
//            for (JCheckBox box : boxes) {
//                if (box.isSelected()) {
//                    System.out.println(box.getText());
//                }
//            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListServiceJDialog dialog = new ListServiceJDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbRoom;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContainer;
    // End of variables declaration//GEN-END:variables
}
