/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.views;

import bkap.dao.impl.RoomDAO;
import bkap.model.Room;
import java.awt.Button;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author hongb
 */
public class ListRoomEmptyJDialog extends javax.swing.JDialog {

    private RoomDAO roomDao = new RoomDAO();
    private List<Room> listRoom;
    private Button b;
    /**
     * Creates new form ListRoomEmptyJDialog
     */
    public ListRoomEmptyJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listRoom = roomDao.findAll();
        pnlShowRoom.setLayout(new GridLayout(3, 5));
        loadTable(listRoom);
    }
    
    private void loadTable(List<Room> listR){
        pnlShowRoom.removeAll();
        pnlShowRoom.setVisible(true);
        pnlShowRoom.validate();
        pnlShowRoom.repaint();
        for (Room data : listR) {
            b = new Button();
            pnlShowRoom.add(b);
            if(data.getStatus() == 0){
                b.setLabel("P "+data.getRoomId()+" (Trống)");
                b.setBackground(Color.decode("#80bfff"));
                b.setEnabled(true);
            }else if(data.getStatus() == 1){
                b.setLabel("P "+data.getRoomId()+" (Có khách)");
                b.setBackground(Color.decode("#5ABD96"));
                b.setEnabled(false);
            }else if(data.getStatus() == 2){
                b.setLabel("P "+data.getRoomId()+" (Đang bảo dưỡng)");
                b.setBackground(Color.gray);
                b.setEnabled(false);
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnGetAll = new javax.swing.JButton();
        btnGetSingle = new javax.swing.JButton();
        btnGetDouble = new javax.swing.JButton();
        pnlShowRoom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnGetAll.setText("Tất cả");
        btnGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnGetAll);

        btnGetSingle.setText("Phòng đơn");
        btnGetSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSingleActionPerformed(evt);
            }
        });
        jPanel1.add(btnGetSingle);

        btnGetDouble.setText("Phòng đôi");
        btnGetDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDoubleActionPerformed(evt);
            }
        });
        jPanel1.add(btnGetDouble);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addComponent(pnlShowRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlShowRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllActionPerformed
        // TODO add your handling code here:
        listRoom = roomDao.findAll();
        loadTable(listRoom);
    }//GEN-LAST:event_btnGetAllActionPerformed

    private void btnGetSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSingleActionPerformed
        // TODO add your handling code here:
        listRoom = roomDao.findAll();
        List<Room> listSingle = new ArrayList<>();
        for (Room data : listRoom) {
            if(data.getTypeId() == 1){
                listSingle.add(data);
            }
        }
        loadTable(listSingle);
    }//GEN-LAST:event_btnGetSingleActionPerformed

    private void btnGetDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDoubleActionPerformed
        // TODO add your handling code here:
        listRoom = roomDao.findAll();
        List<Room> listDouble = new ArrayList<>();
        for (Room data : listRoom) {
            if(data.getTypeId() == 2){
                listDouble.add(data);
            }
        }
        loadTable(listDouble);
    }//GEN-LAST:event_btnGetDoubleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListRoomEmptyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListRoomEmptyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListRoomEmptyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListRoomEmptyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListRoomEmptyJDialog dialog = new ListRoomEmptyJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetAll;
    private javax.swing.JButton btnGetDouble;
    private javax.swing.JButton btnGetSingle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlShowRoom;
    // End of variables declaration//GEN-END:variables
}
